//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public partial class PxBroadPhaseCallback {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PxBroadPhaseCallback(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PxBroadPhaseCallback obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PxBroadPhaseCallback() {
    destroy();
  }

  public virtual void destroy() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NativePINVOKE.delete_PxBroadPhaseCallback(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void onObjectOutOfBounds(PxShape shape, PxActor actor) {
    NativePINVOKE.PxBroadPhaseCallback_onObjectOutOfBounds__SWIG_0(swigCPtr, PxShape.getCPtr(shape), PxActor.getCPtr(actor));
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void onObjectOutOfBounds(PxAggregate aggregate) {
    NativePINVOKE.PxBroadPhaseCallback_onObjectOutOfBounds__SWIG_1(swigCPtr, PxAggregate.getCPtr(aggregate));
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }
  
  private void SwigDirectorConnect() {
    global::System.IntPtr swigDelegate0gcHandlePtr = global::System.IntPtr.Zero;
    if (SwigDerivedClassHasMethod("onObjectOutOfBounds", swigMethodTypes0)) {
      swigDelegate0 = new SwigDelegatePxBroadPhaseCallback_0(SwigDirectoronObjectOutOfBounds__SWIG_0);
      swigDelegate0dispatcher = new SwigDelegatePxBroadPhaseCallback_0_Dispatcher(SwigDirectoronObjectOutOfBounds__SWIG_0_Dispatcher);
      global::System.Runtime.InteropServices.GCHandle swigDelegate0gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(swigDelegate0, global::System.Runtime.InteropServices.GCHandleType.Weak);
      swigDelegate0gcHandlePtr = global::System.Runtime.InteropServices.GCHandle.ToIntPtr(swigDelegate0gcHandle);
    }
    global::System.IntPtr swigDelegate1gcHandlePtr = global::System.IntPtr.Zero;
    if (SwigDerivedClassHasMethod("onObjectOutOfBounds", swigMethodTypes1)) {
      swigDelegate1 = new SwigDelegatePxBroadPhaseCallback_1(SwigDirectoronObjectOutOfBounds__SWIG_1);
      swigDelegate1dispatcher = new SwigDelegatePxBroadPhaseCallback_1_Dispatcher(SwigDirectoronObjectOutOfBounds__SWIG_1_Dispatcher);
      global::System.Runtime.InteropServices.GCHandle swigDelegate1gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(swigDelegate1, global::System.Runtime.InteropServices.GCHandleType.Weak);
      swigDelegate1gcHandlePtr = global::System.Runtime.InteropServices.GCHandle.ToIntPtr(swigDelegate1gcHandle);
    }
    NativePINVOKE.PxBroadPhaseCallback_director_connect(swigCPtr, swigDelegate0dispatcher, swigDelegate0gcHandlePtr, swigDelegate1dispatcher, swigDelegate1gcHandlePtr);
  }
  
  
  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(PxBroadPhaseCallback));
    return hasDerivedMethod;
  }

  private void SwigDirectoronObjectOutOfBounds__SWIG_0(global::System.IntPtr shape, global::System.IntPtr actor) {
    onObjectOutOfBounds(PxShape.getWrapper(shape, false), PxActor.getWrapper(actor, false));
  }

  [NativePINVOKE.MonoPInvokeCallback(typeof(SwigDelegatePxBroadPhaseCallback_0_Dispatcher))]
  private static void SwigDirectoronObjectOutOfBounds__SWIG_0_Dispatcher(global::System.IntPtr swigDelegatePxBroadPhaseCallback_0_Handle, global::System.IntPtr shape, global::System.IntPtr actor) {
    global::System.Runtime.InteropServices.GCHandle gcHandle = global::System.Runtime.InteropServices.GCHandle.FromIntPtr(swigDelegatePxBroadPhaseCallback_0_Handle);
    SwigDelegatePxBroadPhaseCallback_0 delegateSwigDelegatePxBroadPhaseCallback_0 = (SwigDelegatePxBroadPhaseCallback_0) gcHandle.Target;
delegateSwigDelegatePxBroadPhaseCallback_0(shape, actor);
  }

  private void SwigDirectoronObjectOutOfBounds__SWIG_1(global::System.IntPtr aggregate) {
    onObjectOutOfBounds(PxAggregate.getWrapper(aggregate, false));
  }

  [NativePINVOKE.MonoPInvokeCallback(typeof(SwigDelegatePxBroadPhaseCallback_1_Dispatcher))]
  private static void SwigDirectoronObjectOutOfBounds__SWIG_1_Dispatcher(global::System.IntPtr swigDelegatePxBroadPhaseCallback_1_Handle, global::System.IntPtr aggregate) {
    global::System.Runtime.InteropServices.GCHandle gcHandle = global::System.Runtime.InteropServices.GCHandle.FromIntPtr(swigDelegatePxBroadPhaseCallback_1_Handle);
    SwigDelegatePxBroadPhaseCallback_1 delegateSwigDelegatePxBroadPhaseCallback_1 = (SwigDelegatePxBroadPhaseCallback_1) gcHandle.Target;
delegateSwigDelegatePxBroadPhaseCallback_1(aggregate);
  }

  public delegate void SwigDelegatePxBroadPhaseCallback_0(global::System.IntPtr shape, global::System.IntPtr actor);
  public delegate void SwigDelegatePxBroadPhaseCallback_1(global::System.IntPtr aggregate);

  private SwigDelegatePxBroadPhaseCallback_0 swigDelegate0;
  private SwigDelegatePxBroadPhaseCallback_1 swigDelegate1;

  public delegate void SwigDelegatePxBroadPhaseCallback_0_Dispatcher(global::System.IntPtr swigDelegatePxBroadPhaseCallback_0_Handle, global::System.IntPtr shape, global::System.IntPtr actor);
  public delegate void SwigDelegatePxBroadPhaseCallback_1_Dispatcher(global::System.IntPtr swigDelegatePxBroadPhaseCallback_1_Handle, global::System.IntPtr aggregate);

  private SwigDelegatePxBroadPhaseCallback_0_Dispatcher swigDelegate0dispatcher;
  private SwigDelegatePxBroadPhaseCallback_1_Dispatcher swigDelegate1dispatcher;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(PxShape), typeof(PxActor) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(PxAggregate) };

  // private void SwigDirectorConnect() {
  //   if (SwigDerivedClassHasMethod("onObjectOutOfBounds", swigMethodTypes0))
  //     swigDelegate0 = new SwigDelegatePxBroadPhaseCallback_0(SwigDirectorMethodonObjectOutOfBounds__SWIG_0);
  //   if (SwigDerivedClassHasMethod("onObjectOutOfBounds", swigMethodTypes1))
  //     swigDelegate1 = new SwigDelegatePxBroadPhaseCallback_1(SwigDirectorMethodonObjectOutOfBounds__SWIG_1);
  //   NativePINVOKE.PxBroadPhaseCallback_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  // }

  // private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
  //   global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
  //   bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(PxBroadPhaseCallback));
  //   return hasDerivedMethod;
  // }
  //
  // private void SwigDirectorMethodonObjectOutOfBounds__SWIG_0(global::System.IntPtr shape, global::System.IntPtr actor) {
  //   onObjectOutOfBounds(PxShape.getWrapper(shape, false), PxActor.getWrapper(actor, false));
  // }
  //
  // private void SwigDirectorMethodonObjectOutOfBounds__SWIG_1(global::System.IntPtr aggregate) {
  //   onObjectOutOfBounds(PxAggregate.getWrapper(aggregate, false));
  // }
  //
  // public delegate void SwigDelegatePxBroadPhaseCallback_0(global::System.IntPtr shape, global::System.IntPtr actor);
  // public delegate void SwigDelegatePxBroadPhaseCallback_1(global::System.IntPtr aggregate);
  //
  // private SwigDelegatePxBroadPhaseCallback_0 swigDelegate0;
  // private SwigDelegatePxBroadPhaseCallback_1 swigDelegate1;
  //
  // private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(PxShape), typeof(PxActor) };
  // private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(PxAggregate) };
}

}
